"""Describe your changes

Revision ID: 3d36f0e60f2b
Revises: 63da16cca411
Create Date: 2025-09-14 11:09:18.345636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d36f0e60f2b'
down_revision = '63da16cca411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
