"""Doc id null

Revision ID: 5a4e9a4aadaa
Revises: 9714bb670ebb
Create Date: 2025-09-14 14:59:40.997595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4e9a4aadaa'
down_revision = '9714bb670ebb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
