"""Initial migration

Revision ID: 63da16cca411
Revises: 
Create Date: 2025-09-12 13:49:34.475528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63da16cca411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doctor_reports_report_id', table_name='doctor_reports')
    op.drop_table('doctor_reports')
    op.add_column('appointments', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('symptoms', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY', name='urgencylevel'), nullable=True))
    op.add_column('appointments', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('call_bookings', sa.Column('suggested_specialization', sa.String(length=100), nullable=True))
    op.add_column('call_bookings', sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY', name='urgencylevel'), nullable=True))
    op.add_column('call_bookings', sa.Column('call_duration', sa.Integer(), nullable=True))
    op.add_column('call_bookings', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('doctors', sa.Column('qualifications', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('availability', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('doctors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('hospitals', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('hospitals', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('hospitals', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('medical_records', sa.Column('file_name', sa.String(length=200), nullable=True))
    op.add_column('medical_records', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'address')
    op.drop_column('medical_records', 'description')
    op.drop_column('medical_records', 'file_name')
    op.drop_column('hospitals', 'updated_at')
    op.drop_column('hospitals', 'website')
    op.drop_column('hospitals', 'email')
    op.drop_column('doctors', 'updated_at')
    op.drop_column('doctors', 'is_online')
    op.drop_column('doctors', 'availability')
    op.drop_column('doctors', 'bio')
    op.drop_column('doctors', 'qualifications')
    op.drop_column('call_bookings', 'status')
    op.drop_column('call_bookings', 'call_duration')
    op.drop_column('call_bookings', 'urgency')
    op.drop_column('call_bookings', 'suggested_specialization')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'notes')
    op.drop_column('appointments', 'urgency')
    op.drop_column('appointments', 'symptoms')
    op.drop_column('appointments', 'duration')
    op.create_table('doctor_reports',
    sa.Column('report_id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), nullable=True),
    sa.Column('doctor_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('ix_doctor_reports_report_id', 'doctor_reports', ['report_id'], unique=False)
    # ### end Alembic commands ###
