"""Doc id null

Revision ID: 8efbcc6fbd68
Revises: 95c60d3930c6
Create Date: 2025-09-14 14:18:44.065938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efbcc6fbd68'
down_revision = '95c60d3930c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
