"""Doc id null

Revision ID: 95c60d3930c6
Revises: 9a033499203f
Create Date: 2025-09-14 11:14:08.733327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c60d3930c6'
down_revision = '9a033499203f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
