"""Doc id null

Revision ID: 9714bb670ebb
Revises: 8efbcc6fbd68
Create Date: 2025-09-14 14:32:29.089042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9714bb670ebb'
down_revision = '8efbcc6fbd68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
