"""Doc id null

Revision ID: 9a033499203f
Revises: 3d36f0e60f2b
Create Date: 2025-09-14 11:13:39.949770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a033499203f'
down_revision = '3d36f0e60f2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
